  sInvalidPoint             = '无效的点.';
  sRequireValue             = '需要数值';
  sRequirePoint             = '需要点.';
  sRequireKeyword           = '需要选项关键字.';
  sRequirePointOrKeyword    = '需要点或选项关键字.';
  sRequireDisOrPoint        = '需要数值距离或点';

  sLinesParallel            = '线是平行的';
  sRadiusTooLarge           = '半径值太大';
  sDistanceTooLarge         = '距离值太大';
  sEscOrEnterToExit         = '按 Esc 或 Enter 键退出';


  sAPoint                   = '指定点';
  sBasePoint                = '指定基点';
  sFirstPoint               = '指定第一点';
  sSecondPoint              = '指定第二点';
  sThirdPoint               = '指定第三点';

  sNextPoint                = '指定下一个点';
  sNextPointUndo            = '指定下一点[放弃(U)]';
  sThroughPoint             = '指定通过点';

  sCenterPoint              = '指定中心点';
  sCircleCenterPoint        = '指定圆的圆心或 [三点(3P)/两点(2P)]'; // /相切、相切、半径(T)

  sCircleRadius             = '指定圆的半径';
  sInvalidCircleRadius      = '需要数值半径、圆周上的点';
  sCircleFirstPoint         = '指定圆直第一个端点';
  sCircleSecondPoint        = '指定圆直第二个端点';

  sCirclePoint1             = '指定圆第一点';
  sCirclePoint2             = '指定圆第二点';
  sCirclePoint3             = '指定圆第三点';

  sFirstCorner              = '指定第一个角点';
  sFirstCornerOrKeyword     = '指定第一个角点或 [三点(3P)/中心(C)]';
  sSecondCorner             = '指定第二个角点';
  sOtherCorner              = '指定其他角点';
  sSpecifySize              = '指定宽高';

  sRotationAngle            = '指定旋转角度';

  sPolylineStartPnt         = '请指定起点';
  sPolylineNextPntA         = '指定下一个点或 [圆弧(A)/放弃(U)/闭合(C)]';
  sPolylineNextPntL         = '指定下一个点或 [直线(L)/放弃(U)/闭合(C)]';
  sPolylineNextPntA2        = '指定下一点或 [圆弧(A)/闭合(C)/放弃(U)/宽度(W)]';
  sPolylineNextPntL2        = '指定下一点或 [直线(L)/闭合(C)/放弃(U)/宽度(W)]';
  sPolylineStartWidth       = '指定起点宽度';
  sPolylineEndWidth         = '指定端点宽度';
  sPolylineUndone           = '已经放弃所有线段.';

  sSideNumber               = '输入边的数目';
  sPolygonCenter            = '指定正多边形中心点';
  sPolygonOption            = '输入选项 [内切于圆(I)/外切于圆(C)]';
  sPolygonSides             = '需要 3 到 256 之间的整数';

  sArcStartPoint            = '指定圆弧起点';
  sArcStartPointOrKeyword   = '指定圆弧起点 或者 [圆心,起点,端点(C)/圆心,起点,角度(E)/圆心,起点,长度(L)]';
  sArcSecondPoint           = '指定圆弧的第二个点';
  sArcEndPoint              = '指定圆弧的第二个点';

  sIncludedAngle            = '制定夹角';
  sChordLengh               = '指定弦长';

  sEllAxisEndPointOrKeyword = '指定椭圆的轴端点或 [圆弧(A)/中心点(C)]';
  sEllArcAxisEndPointOrCen  = '指定椭圆弧的轴端点或 [中心点(C)]';

  sEllOtherAxisEndPoint     = '指定轴的另一个端点';
  sEllOtherAxisDisOrRot     = '指定另一条半轴长度或 [旋转(R)]';

  sEllStartAngle            = '指定起始角度或参数点';
  sEllEndAngle              = '指定结束角度或参数点';

  sEllCenterPoint           = '指定椭圆的中心点';
  sEllAxisEndPoint          = '指定轴的端点';


  sTextInsertPoint          = '指定文本的插入点';
  sTextHeight               = '指定文本的高度';
  sTextRotation             = '指定文本的高旋转角度';


  sSelectObject             = '选择对象';
  sSelectTextObject         = '选择文本对象';
  sSelectHatchObject        = '选择剖面对象';
  sPickInterPnt             = '选择内部点';


  sMirrorFirstPnt           = '指定镜像线的第一点';
  sMirrorSecondPnt          = '指定镜像线的第二点';


  sOffsetDistance           = '指定偏移长度';
  sSelectOffObject          = '选择偏移对象';
  sOffsetSide               = '指定点以确定偏移所在一侧';
  sCannotToOffset           = '不能偏移这个对象.';

  sRotAngleOrCopy           = '指定旋转角度或 [复制(C)]:';
  sRotCopySelectedObjs      = '复制旋转选中的对象.';

  sScaleFactorOrCopy        = '指定比例因子或 [复制(C)]';
  sScaleCopySelectedObjs    = '复制缩放选中的对象.';

  sSelectToTrim             = '选择要裁剪的对象';
  sCannotToTrim             = '不能裁剪个对象.';


  sSelectToExtend           = '选择要拉伸的对象';
  sCannotToExtend           = '不能拉伸这个对象.';


  sSpecifyBreakPoint1       = '指定第一个打断点';
  sSpecifyBreakPoint2       = '指定第二个打断点';
  sCannotToBreak            = '不能打断这个对象';


  sChamferStatus            = '当前倒角距离1 = %g, 距离2 = %g';
  sFilletStatus             = '当前圆角半径 = %g';

  sChamferLine1OrKeyword    = '选择第一条直线或 [多段线(P)/距离(D)/修剪(T)]'; //  Undo/ /mEthod/Multiple
  sChamferLine2             = '选择第二条直线';
  sChamferDis1              = '指定第一个倒角距离';
  sChamferDis2              = '指定第二个倒角距离';
  sChamferReq2Lines         = '倒角需要两条直线';
  sChamferError             = '这两个图元之间无法倒角';

  sFilletObj1OrKeyword      = '选择第一个对象或 [多段线(P)/半径(R)/修剪(T)]'; // Undo/   /Multiple
  sFilletObj2               = '选择第二个对象';
  sFilletRadius             = '指定圆角半径';
  sFilletError              = '这两个图元之间无法圆角';

  sTrimMode                 = '输入修剪模式选项 [修剪(T)/不修剪(N)]';
  sSelectPolyline           = '选择多段线';

  sScaleFactor              = '输入比例因子 (nX 或 nXP)';
  sZoomCmd1                 = '指定窗口角点，输入比例因子 (nX 或 nXP)，或';
  sZoomCmd2                 = '[全部(A)/中心点(C)/动态(D)/范围(E)/上一个(P)/比例(S)/窗口(W)] <实时>';

  sStretchPointOrKeyword    = '指定拉伸点或 [基点(B)/复制(C)/放弃(U)/退出(X)]';

  sStretchName              = '** 拉伸 **';
  sMuliStretchName          = '** 拉伸 (多重) **';

  sSelectObjectsNum         = '选择对象: 选中 %d 个, 共 %d 个';

  //---------------------------------------------------------------------------

  sCurrRectModes        = '当前矩形模式';
  sChamferName          = '倒角';
  sFilletName           = '圆角';
  sWidthName            = '线宽';
  sRotationName         = '旋转角度';

  sRectP1OrKeys         = '指定第一个角点或 [倒角(C)/圆角(F)/宽度(W)]';
  sRectP2OrKeys         = '指定另一个角点或 [旋转角度(R)]';//  Area/Dimensions/
  sRectChamfer1         = '指定矩形的第一个倒角距离';
  sRectChamfer2         = '指定矩形的第二个倒角距离';
  sRectFillet           = '指定矩形的圆角半径';
  sRectWidth            = '指定矩形的线宽';

  sXLinePntOrKeys       = '指定点或 [水平(H)/垂直(V)/角度(A)/偏移(O)]';
  sEnterXLineAng        = '输入构造线的角度';
  sXLineOffDisOrKeys    = '指定偏移距离或 [通过(T)]';
  sSelLineObj           = '选择一个线对象';
  sNoUsableObjSel       = '无有效对象被选中';

  sDonutInsideDia       ='指定圆环的内径';
  sDonutOutsideDia      ='指定圆环的外径';
  sDonutCenterPnt       ='指定圆环的中心点';



  sInvalidSelection     = '*无效选择*';
  sNoObjFound           = '没有发现对象';
  sSelectDimObject      = '选择标注';
  sNoDimObjectSelected  = '没有标注对象被选中.';

  sDimFirstExtOrgn      = '指定第一条尺寸界线原点';
  sDimSecondExtOrgn     = '指定第二条尺寸界线原点';

  sDimLinePntOr         = '指定第一条尺寸界线原点或';
  sDimLineKeys1         = '[文字(T)/角度(A)/水平(H)/垂直(V)/旋转(R)]';
  sDimLineKeys2         = '[文字(T)/角度(A)]';

  sDimTextAngle         = '指定标注文本的角度';
  sDimTextIs            = '标注文本 =';
  sEnterDimText         = '输入标注文本';
  sEnterDimAngle        = '指定标注线的角度';


  sSelArcOrPolyArc      = '选择弧线对象或多边形的弧线段';
  sArcLenDimPnt         = '指定弧线长度标注的原点';
  sArcLenDimPntOrKeys   = '指定弧线长度标注的原点, 或 [文本(T)/角度(A)/部分弧线(P)/箭头(L)]';
  sArcLenDimPntOrKeys2  = '指定弧线长度标注的原点, 或 [文本(T)/角度(A)/部分弧线(P)/无箭头(N)]';

  sArcLenDimArcPnt1     = '指定弧线长度标注的第一个点';
  sArcLenDimArcPnt2     = '指定弧线长度标注的第二个点';

  sSelectArcOrCir       = '选择圆弧或圆';
  sSelectSecondLine     = '选择第二个线';
  sRadialDimPntOrKeys   = '选择标注线的原点或 [文本(T)/角度(A)]';

  sSelectAngle1Pnt      = '指定角的第一个端点';
  sSelectAngle2Pnt      = '指定角的第二个端点';
  sSelectArcCirLine     = '选择圆弧、圆、直线';
  sAngularDimPntOrKeys  = '指定标注弧线位置或 [文本(T)/角度(A)]';

  sOverridePoint        = '指定图示中心位置';
  sJogPoint             = '指定折弯位置';

  sFeaturePoint         = '指定点坐标';
  sLeaderEndPntOrKeys   = '指定引线端点或 [X 基准(X)/Y 基准(Y)/文字(T)/角度(A)]';

  sInvalidCenterKind    = '点样式的尺寸为0或样式为空. *无效*';

  sEnterTolPoint        = '输入公差位置';

  sFirstLeaderPnt       = '指定第一个引线点';
  sFirstLineOfText      = '输入注释文字的第一行';
  sNextLineOfText       = '输入注释文字的下一行';

  sSelBaseDim           = '选择基准标注';
  sNeedLnOrAngDim       = '需要线性、坐标或角度关联标注.';
  sSecondExtPntOrUndo   = 'Specify a second extension line origin'; // or [Undo]

  sEditDimTextAlign     = '指定编辑标注的类型 [左(L)/右(R)/中心(C)/默认(H)/角度(A)] <默认(H)>';
  sEditDimTextEdit      = '指定标注文字的新位置或 [左(L)/右(R)/中心(C)/默认(H)/角度(A)]';


  //-----------------------------------------

  sDisBetweenRows       = '指定行间距';
  sDisBetweenColumns    = '指定列间距';
  sAngleOfArray         = '指定阵列角度';
  sCenterOfArray        = '指定阵列中心点';
  sAngleOfFill          = '指定阵列中心点';

  sInsBasePoint         = '插入点';
  sScaleXFactor         = '输入X向比例';
  sScaleYFactor         = '输入X向比例';
  sUseScaleYFactor      = '使用X向比例';


  sFirstCornerOrObj     = '指定第一个角点或 [对象(O)]';
  sNextPointOrEnter     = '指定下一个角点或按 ENTER 键全选';
  sObjectHasNoArea      = '选择的对象没有面积';
  sEnterObjOrdering     = '输入对象排序选项[置前(A)/置后(U)/最前(F)/最后(B)] <最后(B)>';
  sSelectRefObjs        = '选择参照对象';
  sCannotUseSameObj     = '不能使用同一对象';

  sSelectSrcObject      = '选择源对象';
  sSelectDstObject      = '选择目标对象';