  sInvalidPoint             = 'Invalid Point.';
  sRequireValue             = 'number required';
  sRequirePoint             = 'Point required.';
  sRequireKeyword           = 'option keyword required.';
  sRequirePointOrKeyword    = 'Point or option keyword required.';
  sRequireDisOrPoint        = 'Distance num or point required.';

  sLinesParallel            = 'Lines are parallel';
  sRadiusTooLarge           = 'Radius is too large';
  sDistanceTooLarge         = 'Distance is too large';
  sEscOrEnterToExit         = 'Press ESC or ENTER to exit';


  sAPoint                   = 'Specify a point';
  sBasePoint                = 'Specify base point';
  sFirstPoint               = 'Specify first point';
  sSecondPoint              = 'Specify second point';
  sThirdPoint               = 'Specify third point';

  sNextPoint                = 'Specify next point';
  sNextPointUndo            = 'Specify next point or [Undo]';
  sThroughPoint             = 'Specify through point';

  sCenterPoint              = 'Specify center point';
  sCircleCenterPoint        = 'Specify center point for circle or [3P/2P]'; ///Ttr (tan tan radius)

  sCircleRadius             = 'Specify radius of circle';
  sInvalidCircleRadius      = 'Requires numeric distance, second point';
  sCircleFirstPoint         = 'Specify first end point of circle';
  sCircleSecondPoint        = 'Specify second end point of circle';

  sCirclePoint1             = 'Specify first point on circle';
  sCirclePoint2             = 'Specify second point on circle';
  sCirclePoint3             = 'Specify third point on circle';

  sFirstCorner              = 'Specify first corner point';
  sFirstCornerOrKeyword     = 'Specify first corner point or [3P/Center]';
  sSecondCorner             = 'Specify second corner point';
  sOtherCorner              = 'Specify other corner point';
  sSpecifySize              = 'Specify size';

  sRotationAngle            = 'Specify rotation angle';

  sPolylineStartPnt         = 'Specify start point';
  sPolylineNextPntA         = 'Specify next point or [Arc/Undo/Width]';
  sPolylineNextPntL         = 'Specify next point or [Line/Undo/Width]';
  sPolylineNextPntA2        = 'Specify next point or [Arc/Close/Undo/Width]';
  sPolylineNextPntL2        = 'Specify next point or [Line/Close/Undo/Width]';
  sPolylineStartWidth       = 'Specify starting width';
  sPolylineEndWidth         = 'Specify ending width';
  sPolylineUndone           = 'All segments already undone.';

  sSideNumber               = 'Enter number of sides';
  sPolygonCenter            = 'Specify center of polygon';
  sPolygonOption            = 'Enter an option [Inscribed in circle/Circumscribed about circle]';
  sPolygonSides             = 'Requires an integer between 3 and 256';

  sArcStartPoint            = 'Specify start point of arc';
  sArcStartPointOrKeyword   = 'Specify start point of arc or [Center,Start,End(C)/Center,Start,Angle(E)/Center,Start,System.Length(L)]';
  sArcSecondPoint           = 'Specify second point of arc';
  sArcEndPoint              = 'Specify end point of arc';

  sIncludedAngle            = 'Specify included angle';
  sChordLengh               = 'Specify length of chord';

  sEllAxisEndPointOrKeyword = 'Specify axis endpoint of ellipse or [Arc/Center]';
  sEllArcAxisEndPointOrCen  = 'Specify axis endpoint of elliptical arc or [Center]';

  sEllOtherAxisEndPoint     = 'Specify other endpoint of axis';
  sEllOtherAxisDisOrRot     = 'Specify distance to other axis or [Rotation]';

  sEllStartAngle            = 'Specify start angle or parameter';
  sEllEndAngle              = 'Specify end angle or parameter';

  sEllCenterPoint           = 'Specify center of ellipse';
  sEllAxisEndPoint          = 'Specify endpoint of axis';


  sTextInsertPoint          = 'Specify text insertion point';
  sTextHeight               = 'Specify text height';
  sTextRotation             = 'Specify rotation angle of text';


  sSelectObject             = 'Select objects';
  sSelectTextObject         = 'Select text object';
  sSelectHatchObject        = 'Select hatch object';
  sPickInterPnt             = 'Pick internal point';

  sMirrorFirstPnt           = 'Specify first point of mirror line';
  sMirrorSecondPnt          = 'Specify second point of mirror line';


  sOffsetDistance           = 'Specify offset distance';
  sSelectOffObject          = 'Select object to offset';
  sOffsetSide               = 'Specify point on side to offset';
  sCannotToOffset           = 'Cannot offset that object.';

  sRotAngleOrCopy           = 'Specify rotation angle or [Copy]';
  sRotCopySelectedObjs      = 'Rotating a copy of the selected objects.';

  sScaleFactorOrCopy        = 'Specify scale factor or [Copy]';
  sScaleCopySelectedObjs    = 'Scaling a copy of the selected objects.';

  sSelectToTrim             = 'Select object to trim';
  sCannotToTrim             = 'Object does not intersect an edge.';


  sSelectToExtend           = 'Select object to extend';
  sCannotToExtend           = 'Can''t extend this object';


  sSpecifyBreakPoint1       = 'Specify first break point';
  sSpecifyBreakPoint2       = 'Specify second break point';
  sCannotToBreak            = 'Can''t break this object';


  sChamferStatus            = 'Current chamfer Dist1 = %f, Dist2 = %f';
  sFilletStatus             = 'Current fillet radius = %f';

  sChamferLine1OrKeyword    = 'Select first line or [Polyline/Distance/Trim]'; //  Undo/ Angle/ /mEthod/Multiple
  sChamferLine2             = 'Select second line or shift-select to apply corner';
  sChamferDis1              = 'Specify first chamfer distance';
  sChamferDis2              = 'Specify second chamfer distance';
  sChamferReq2Lines         = 'Chamfer requires 2 lines';
  sChamferError             = 'Cannot chamfer between these two entities';

  sFilletObj1OrKeyword      = 'Select first object or [Polyline/Radius/Trim]'; // Undo/   /Multiple
  sFilletObj2               = 'Select second object or shift-select to apply corner';
  sFilletRadius             = 'Specify fillet radius';
  sFilletError              = 'Unable to fillet curves';

  sTrimMode                 = 'Enter Trim mode option [Trim/No trim]';
  sSelectPolyline           = 'Select polyline';

  sScaleFactor              = 'Enter a scale factor (nX or nXP)';
  sZoomCmd1                 = 'Specify corner of window, enter a scale factor (nX or nXP), or';
  sZoomCmd2                 = '[All/Center/Extents/Previous/Scale/Window/Object] <real time>';

  sStretchPointOrKeyword    = 'Specify stretch point or [Base point/Copy/Undo/eXit]';

  sStretchName              = '** STRETCH **';
  sMuliStretchName          = '** STRETCH (multiple) **';

  sSelectObjectsNum         = 'Select objects: %d found, %d total';
  
  //---------------------------------------------------------------------------

  sCurrRectModes        = 'Current rectangle modes';
  sChamferName          = 'Chamfer';
  sFilletName           = 'Fillet';
  sWidthName            = 'Width';
  sRotationName         = 'Rotation';

  sRectP1OrKeys         = 'Specify first corner point or [Chamfer/Fillet/Width]';
  sRectP2OrKeys         = 'Specify other corner point or [Rotation]';//  Area/Dimensions/
  sRectChamfer1         = 'Specify first chamfer distance for rectangles';
  sRectChamfer2         = 'Specify second chamfer distance for rectangles';
  sRectFillet           = 'Specify fillet radius for rectangles';
  sRectWidth            = 'Specify line width for rectangles';

  sXLinePntOrKeys       = 'Specify a point or [Hor/Ver/Ang/Offset]';
  sEnterXLineAng        = 'Enter angle of xline';
  sXLineOffDisOrKeys    = 'Specify offset distance or [Through]';
  sSelLineObj           = 'Select a line object';
  sNoUsableObjSel       = 'No usable object selected';

  sDonutInsideDia       ='Specify inside diameter of donut';
  sDonutOutsideDia      ='Specify outside diameter of donut';
  sDonutCenterPnt       ='Specify center of donut';



  sInvalidSelection     = '*Invalid selection*';
  sNoObjFound           = 'No Object Found';
  sSelectDimObject      = 'Select dimension';
  sNoDimObjectSelected  = 'No dimension object selected.';

  sDimFirstExtOrgn      = 'Specify first extension line origin';
  sDimSecondExtOrgn     = 'Specify second extension line origin';

  sDimLinePntOr         = 'Specify dimension line location or';
  sDimLineKeys1         = '[Text/Angle/Horizontal/Vertical/Rotated]';
  sDimLineKeys2         = '[Text/Angle]';

  sDimTextAngle         = 'Specify angle of dimension text';
  sDimTextIs            = 'Dimension text =';
  sEnterDimText         = 'Enter dimension text';
  sEnterDimAngle        = 'Specify angle of dimension line';


  sSelArcOrPolyArc      = 'Select arc or polyline arc segment';
  sArcLenDimPnt         = 'Specify arc length dimension location';
  sArcLenDimPntOrKeys   = 'Specify arc length dimension location, or [Text/Angle/Partial/Leader]';
  sArcLenDimPntOrKeys2  = 'Specify arc length dimension location, or [Text/Angle/Partial/No leader]';

  sArcLenDimArcPnt1     = 'Specify first point for arc length dimension';
  sArcLenDimArcPnt2     = 'Specify second point for arc length dimension';

  sSelectArcOrCir       = 'Select arc or circle';
  sSelectSecondLine     = 'Select second line';
  sRadialDimPntOrKeys   = 'Specify dimension line location or [Text/Angle]';

  sSelectAngle1Pnt      = 'Specify first angle endpoint';
  sSelectAngle2Pnt      = 'Specify second angle endpoint';
  sSelectArcCirLine     = 'Select arc, circle, line';
  sAngularDimPntOrKeys  = 'Specify dimension arc line location or [Text/Angle]';

  sOverridePoint        = 'Specify center location override';
  sJogPoint             = 'Specify jog location';

  sFeaturePoint         = 'Specify feature location';
  sLeaderEndPntOrKeys   = 'Specify leader endpoint or [Xdatum/Ydatum/Text/Angle]';

  sInvalidCenterKind    = 'Center make size = 0.0, not drawing center cross. *Invalid*';

  sEnterTolPoint        = 'Enter tolerance location';

  sFirstLeaderPnt       = 'Specify first leader point';
  sFirstLineOfText      = 'Enter first line of annotation text';
  sNextLineOfText       = 'Enter next line of annotation text';

  sSelBaseDim           = 'Select base dimension';
  sNeedLnOrAngDim       = 'Linear or Angular Associative Dimension Required.';
  sSecondExtPntOrUndo   = 'Specify a second extension line origin'; // or [Undo]

  sEditDimTextAlign     = 'Enter type of dimension editing [Left/Right/Center/Home/Angle] <Home>';
  sEditDimTextEdit      = 'Specify new location for dimension text or [Left/Right/Center/Home/Angle]';


  //-----------------------------------------

  sDisBetweenRows       = 'Specify the distance between rows';
  sDisBetweenColumns    = 'Specify the distance between columns';
  sAngleOfArray         = 'Specify angle of array';
  sCenterOfArray        = 'Specify center point of array';
  sAngleOfFill          = 'Specify the angle to fill';

  sInsBasePoint         = 'Specify insertion base point';
  sScaleXFactor         = 'Enter X scale factor';
  sScaleYFactor         = 'Enter Y scale factor';
  sUseScaleYFactor      = 'use X scale factor';


  sFirstCornerOrObj     = 'Specify first corner point or [Object]';
  sNextPointOrEnter     = 'Specify next corner point or press ENTER for total';
  sObjectHasNoArea      = 'Selected object does not have an area';
  sEnterObjOrdering     = 'Enter object ordering option [Above objects/Under objects/Front/Back] <Back>';
  sSelectRefObjs        = 'Select reference objects';
  sCannotUseSameObj     = 'Cannot use same object';

  sSelectSrcObject      = 'Select source object';
  sSelectDstObject      = 'Select destination object(s)';
